import { Component } from '@angular/core';
import { PatternValidator } from '@angular/forms';
enum RegExpEnum{
    DiVIDE_PAR_0="^[0-9]\\/0*$"
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  availableRegex=RegExpEnum
  op1=""
  op2=""
  operateur=""
  i=0
  j=0
  response=""
  reponseResultat=0

  showMessage=false
  disable=false
  messageErreur="veuillez choisir un chiffre"
  operation=""

  setOp1(op1:String){
    this.op1=this.op1+op1
  }
  setOp2(op2:String){
    this.op2=this.op2+op2
  }
  setOperation(operation:String){
    this.operation=this.operation+operation
  }
  getOperation(){
    return this.operation
  }
  function1(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("1")
      this.setOperation("1")
    }else{
      if(this.operateur==""){
        this.setOp1("1")
        this.setOperation("1")
      }else{
        this.setOp2("1")
        this.setOperation("1")
      }
    }
    console.log(this.op1)
  }
  function2(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("2")
      this.setOperation("2")
    }else{
      if(this.operateur==""){
        this.setOp1("2")
        this.setOperation("2")
      }else{
        this.setOp2("2")
        this.setOperation("2")
      }
    }
  }
  function3(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("3")
      this.setOperation("3")
    }else{
      if(this.operateur==""){
        this.setOp1("3")
        this.setOperation("3")
      }else{
        this.setOp2("3")
        this.setOperation("3")
      }
    }
  }
  function4(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("4")
      this.setOperation("4")
    }else{
      if(this.operateur==""){
        this.setOp1("4")
        this.setOperation("4")
      }else{
        this.setOp2("4")
        this.setOperation("4")
      }
    }
  }
  function5(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("5")
      this.setOperation("5")
    }else{
      if(this.operateur==""){
        this.setOp1("5")
        this.setOperation("5")
      }else{
        this.setOp2("5")
        this.setOperation("5")
      }
    }
  }
  function6(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("6")
      this.setOperation("6")
    }else{
      if(this.operateur==""){
        this.setOp1("6")
        this.setOperation("6")
      }else{
        this.setOp2("6")
        this.setOperation("6")
      }
    }
  }
  function7(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("7")
      this.setOperation("7")
    }else{
      if(this.operateur==""){
        this.setOp1("7")
        this.setOperation("7")
      }else{
        this.setOp2("7")
        this.setOperation("7")
      }
    }
  }
  function8(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("8")
      this.setOperation("8")
    }else{
      if(this.operateur==""){
        this.setOp1("8")
        this.setOperation("8")
      }else{
        this.setOp2("8")
        this.setOperation("8")
      }
    console.log(this.op1)
  }
}
  function9(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("9")
      this.setOperation("9")
    }else{
      if(this.operateur==""){
        this.setOp1("9")
        this.setOperation("9")
      }else{
        this.setOp2("9")
        this.setOperation("9")
      }
    }
  }
  function0(){
    this.showMessage=false
    if(this.operation==""){
      this.setOp1("0")
      this.setOperation("0")
    }else{
      if(this.operateur==""){
        this.setOp1("0")
        this.setOperation("0")
      }else{
        this.setOp2("0")
        this.setOperation("0")
      }
    }
    console.log(this.op1)
  }
  functionadd(){
    if(this.op1==""){
      this.showMessage=true
    }else{
      this.operateur="+"
      this.setOperation(this.operateur)
    }
  }
  functionsub(){
    if(this.op1==""){
      this.showMessage=true
    }else{
      this.operateur="-"
      this.setOperation(this.operateur)
    }
  }
  functionmup(){
    if(this.op1==""){
      this.showMessage=true
    }else{
      this.operateur="*"
      this.setOperation(this.operateur)
    }
  }
  functiondiv(){
    if(this.op1==""){
      this.showMessage=true
    }else{
      this.operateur="/"
      this.setOperation(this.operateur)
    }
  }
  effacer(){
    this.operation=""
    this.operateur=""
    this.op1=""
    this.op2=""
    this.response=""
  }
  delete(){
    
  }
  
  afficherResultat(){
    this.i=parseInt(this.op1)
    this.j=parseInt(this.op2)
    console.log(this.operation)
    console.log(this.op1)
    console.log(this.op2)
    this.operation=""

    if(!this.operation.includes("/ * + -")){
      this.reponseResultat=this.i
      this.response=""+this.reponseResultat+""
      console.log(this.operation)
      this.setOperation(this.response)
    }


    if(this.operateur=="+"){
      if(this.op1==""){
        this.operation=""
        this.setOperation("MATH ERROR")
      }else{
      this.operation=""
      this.reponseResultat=this.i+this.j
      this.response=""+this.reponseResultat+""
      this.setOperation(this.response)
      }
    }
    if(this.operateur=="-"){
      if(this.op1==""){
        this.operation=""
        this.setOperation("MATH ERROR")
      }else{
      this.operation=""
      this.reponseResultat=this.i-this.j
      this.response=""+this.reponseResultat+""
      this.setOperation(this.response)
      }
    }
    if(this.operateur=="/"){
      if(this.op1=""){
        this.operation=""
        this.setOperation("MATH ERROR")
      }else{
      if(this.op2=="0"){
        this.operation=""
        this.setOperation("MATH ERROR")
      }else{
        this.operation=""
        this.reponseResultat=this.i/this.j
        this.response=""+this.reponseResultat+""
        this.setOperation(this.response)
      }
    }
    }
    if(this.operateur=="*"){
      if(this.op1=""){
        this.operation=""
        this.setOperation("MATH ERROR")
      }else{
      this.operation=""
      this.reponseResultat=this.i*this.j
      this.response=""+this.reponseResultat+""
      this.setOperation(this.response)
      }
    }
  }
}
